local function random_pos()
	return vmath.vector3(math.random(640), math.random(1136), 0)
end

function init(self)
	gui.set_position(gui.get_node("box1"), random_pos())
	gui.set_position(gui.get_node("box2"), random_pos())
	gui.set_text(gui.get_node("text"), tostring(self))
end

function final(self)
	-- Add finalization code here
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add input-handling code here
	-- Remove this function if not needed
end
